config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get '/about', to: 'homes#about', as: 'about'
  get 'searches/search'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get 'followers', to: 'relationships#followers'
      get 'following', to: 'relationships#following'
    end
  end
  resources :books, except: :new do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :book
  counter_culture :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  counter_culture :book
  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates :follower_id, uniqueness: { scope: :followed_id }

  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  counter_culture :follower, column_name: 'following_count'
  counter_culture :followed, column_name: 'followers_count'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, length: { in: 2..20}
  validates :introduction, length: { maximum: 50 }

  has_one_attached :image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def followed?(user)
    self.active_relationships.map { |active_relationship| active_relationship[:followed_id] }.include?(user.id)
  end

  def favorited?(book)
    self.favorites.map { |favorite| favorite[:book_id] }.include?(book.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
      root_path
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book_comment =  current_user.book_comments.create(book_comment_params)
    @book = Book.find(params[:book_id])
  end

  def destroy
    current_user.book_comments.find(params[:id]).destroy
    @book = Book.find(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:body, :book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.eager_load(user: :image_attachment)
  end

  def show
    @book = Book.eager_load(:user).preload(book_comments: :user).find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def create
    @new_book = current_user.books.new(book_params)
    if @new_book.save
      redirect_to book_path(@new_book)
      flash[:notice] = 'You have created book successfully.'
    else
      @books = Book.eager_load(user: :image_attachment).preload(:favorites)
      render :index
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :body)
    end

    def ensure_correct_user
      @book = Book.eager_load(:user).find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book.favorites.create(user_id: current_user.id)
    @book.reload
  end

  def destroy
    current_user.favorites.find_by(book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.active_relationships.create(followed_id: params[:user_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.active_relationships.find_by(followed_id: params[:user_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  def followers
    @users = User.find(params[:id]).followers.with_attached_image
  end

  def following
    @users = User.find(params[:id]).following.with_attached_image
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    keyword = params[:keyword]
    case params[:model]
    when "book"
      models = Book.includes(user: :image_attachment)
      colomn = "title"
    when "user"
      models = User.all
      colomn = "name"
    end

    @searched_models =
    case params[:parameter]
    when "exact_match"
      models.where("#{colomn} = ?","#{keyword}")
    when "forward_match"
      models.where("#{colomn} LIKE?","#{keyword}%")
    when "backward_match"
      models.where("#{colomn} LIKE?","%#{keyword}")
    when "pattern_match"
      models.where("#{colomn} LIKE?","%#{keyword}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.eager_load(:image_attachment)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :introduction, :image)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def create_favorite_book_ids
    @favorite_book_ids = current_user.favorites.pluck(:book_id)
  end

  def create_following_ids
    @following_ids = current_user.following.pluck(:id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comment.html.erb
<tr class='book_comment_<%= book_comment.id %>'>
  <td><%= book_comment.user.name %></td>
  <td><%= book_comment.body %></td>
  <td>
    <% if book_comment.user == current_user %>
      <%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, remote:true %>
    <% end %>
  </td>
</tr>

app/views/book_comments/_form.html.erb
<%= form_with model: [@book, BookComment.new], local: false do |f| %>
 <%= f.text_area :body, class:"comment-form" %>
 <%= f.hidden_field :book_id, value:@book.id %><br>
 <%= f.submit '送信' %>
<% end %>

app/views/book_comments/_list.html.erb
<h2>BookComments</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>body</th>
      <th></th>
    </tr>
  </thead>
  <tbody class='book_comments'>
    <%= render book_comments %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$(".book_comments").append("<%= j(render @book_comment ) %>")
$(".book_comment_count_<%= params[:book_id] %>").text("コメント数：<%= @book.book_comments_count %>");
$(".comment-form").val("");

app/views/book_comments/destroy.js.erb
$(".book_comment_<%= params[:id] %>").remove();
$(".book_comment_count_<%= params[:book_id] %>").text("コメント数：<%= @book.book_comments_count %>");

app/views/books/_book.html.erb
<tr>
  <td>
    <%= link_to user_path(book.user) do %>
      <% if book.user.image.attached? %>
        <%= image_tag book.user.image.variant( resize: '40') %>
      <% else %>
        <%= image_tag 'no_image.jpg', size: '40x40' %>
      <% end %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
  <%= render 'favorites/favorite', book:book %>
  <td>コメント数：<%= book.book_comments_count %></td>
</tr>

app/views/books/_book_form.html.erb
<h2>New book</h2>
<%= form_with model: @new_book ||= Book.new , local:true do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/books/_list.html.erb
<h2>Books</h2>
<table>
  <thead>
    <tr>
      <th>image</th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Favorites</th>
      <th>comments</th>
    </tr>
  </thead>
  <tbody>
    <%= render books %>
  </tbody>
</table>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_with model: @book , local:true do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>
<%= link_to 'Show', book_path(@book) %> | <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if @new_book %>
  <%= render "devise/shared/error_messages", resource: @new_book %>
<% end %>
<%= render 'users/user_info', user:@user %>
<%= render 'books/book_form' %>
<%= render 'books/list', books:@books %>

app/views/books/show.html.erb
<%= render 'users/user_info' %>
<%= render 'books/book_form' %>
<h2>Book detail</h2>
<table>
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@book.user) do %>
          <% if @book.user.image.attached? %>
            <%= image_tag @book.user.image.variant( resize: '40') %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: '40x40' %>
          <% end %><br>
          <%= @book.user.name %>
        <% end %>
      </td>
      <td><%= @book.title %></td>
      <td><%= @book.body %></td>
      <td><%= render 'favorites/favorite', book:@book %></td>
      <td class='book_comment_count_<%= @book.id %>'>コメント数：<%= @book.book_comments_count %></td>
      <% if @book.user == current_user %>
        <td><%= link_to 'Edit', edit_book_path(@book) %></td>
        <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' } %></td>
      <% end %>
    </tr>
  </tbody>
</table>
<%= render 'book_comments/list', book_comments:@book.book_comments %>
<%= render 'book_comments/form' %>

app/views/favorites/_favorite.html.erb
<td class="book_favorite_<%= book.id %>">
  <%= book.favorites_count %>
  <% if current_user.favorited?(book) %>
    <%= link_to 'いいねを解除する', book_favorite_path(book), method: :delete, remote: true %>
  <% else %>
    <%= link_to 'いいねをする', book_favorite_path(book), method: :post, remote: true %>
  <% end %>
</td>

app/views/favorites/create.js.erb
$('.book_favorite_<%= params[:book_id] %>').replaceWith('<%= j(render 'favorites/favorite', book:@book ) %>')

app/views/favorites/destroy.js.erb
$('.book_favorite_<%= params[:book_id] %>').replaceWith('<%= j(render 'favorites/favorite', book:@book ) %>')

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/_header.html.erb
<header>
  <% if user_signed_in? %>
    <nav class='nav'>
      <ul class='nav__list'>
        <li class='nav__item'><%= link_to 'Bookers', root_path %></li>
        <li class='nav__item'><%= link_to 'Home', user_path(current_user) %></li>
        <li class='nav__item'><%= link_to 'Users', users_path %></li>
        <li class='nav__item'><%= link_to 'Books', books_path %></li>
        <li class='nav__item'><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      </ul>
    </nav>
    <%= render 'searches/form' %>
  <% else %>
    <nav class='nav'>
      <ul class='nav__list'>
        <li class='nav__item'><%= link_to 'Bookers', root_path %></li>
        <li class='nav__item'><%= link_to 'Home', root_path %></li>
        <li class='nav__item'><%= link_to 'About', about_path %></li>
        <li class='nav__item'><%= link_to 'Sign up', new_user_registration_path %></li>
        <li class='nav__item'><%= link_to 'Log in', new_user_session_path %></li>
      </ul>
    </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/relationships/_botton.html.erb
<% unless user == current_user %>
  <% if current_user.followed?(user) %>
    <%= link_to 'フォローを外す', user_relationships_path(user), method: :delete %>
  <% else %>
    <%= link_to 'フォローをする', user_relationships_path(user), method: :post %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Followers Users</h2>
<%= render 'users/list', users:@users %>

app/views/relationships/following.html.erb
<h2>Following Users</h2>
<%= render 'users/list', users:@users %>

app/views/searches/_form.html.erb
<%= form_with url: searches_search_path, method: :get, local: true do |f| %>
  <%= f.text_field :keyword %>
  <%= f.select :model, [["Book","book"],["User","user"]] %>
  <%= f.select :parameter,[["完全一致","exact_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","pattern_match"]] %>
  <%= f.submit "検索" %>
<% end %>

app/views/searches/search.html.erb
<% case params[:model] %>
<% when "user" %>
  <h2>Users search for "<%= params[:keyword] %>"</h2>
  <%= render 'users/list', users: @searched_models %>
<% when "book" %>
  <h2>Books search for "<%= params[:keyword] %>"</h2>
  <%= render 'books/list', books: @searched_models %>
<% end %>

app/views/users/_list.html.erb
<h2>Users</h2>
<table>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render users %>
  </tbody>
</table>

app/views/users/_user.html.erb
<tr>
  <td>
    <% if user.image.attached? %>
      <%= image_tag user.image.variant( resize: '40') %>
    <% else %>
      <%= image_tag 'no_image.jpg', size: '40x40' %>
    <% end %>
  </td>
  <td><%= user.name %></td>
  <td>フォロー数：<%= user.following_count %></td>
  <td>フォロワー数：<%= user.followers_count %></td>
  <td class='user_relationships_botton_<%= user.id %>'><%= render 'relationships/botton', user: user %></td>
  <td><%= link_to 'show', user_path(user) %></td>
</tr>

app/views/users/_user_info.html.erb
<% @user ||= current_user %>
<h2>User info</h2>
<% if @user.image.attached? %>
  <%= image_tag @user.image.variant( resize: '100') %>
<% else %>
  <%= image_tag 'no_image.jpg', size: '100x100' %>
<% end %>
<table>
  <thead>
    <tr>
      <th>name:</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>introduction:</th>
      <th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>following:</th>
      <th>
        <%= link_to following_user_path(@user) do %>
          <%= @user.following_count %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>followers:</th>
      <th>
        <%= link_to followers_user_path(@user) do %>
          <%= @user.followers_count %>
        <% end %>
      </th>
    </tr>
  </thead>
</table>
<% if @user == current_user %>
  <%= link_to 'ユーザー設定', edit_user_path(@user) %>
<% else %>
  <%= render 'relationships/botton', user: @user %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= render "devise/shared/error_messages", resource: @user %>
<%= form_with model: @user , local:true do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :image %><br>
  <%= f.file_field :image %><br>
  <%= f.label :introduction %><br>
  <%= f.text_area :introduction %><br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<%= render 'users/user_info' %>
<%= render 'books/book_form' %>
<%= render 'users/list', users:@users %>

app/views/users/show.html.erb
<%= render 'users/user_info', user:@user %>
<%= render 'books/book_form' %>
<%= render 'books/list', books:@user.books %>